"""Markdown formatter for Triage Memos."""

from triage_agent.models.memo import TriageMemo


def render_markdown(memo: TriageMemo) -> str:
    """Render a TriageMemo as a readable Markdown document.

    Args:
        memo: The completed TriageMemo to format.

    Returns:
        A Markdown string ready for display or saving to file.
    """
    sections: list[str] = []
    novelty_report = memo.novelty_report
    local_overlap = memo.local_overlap

    # Header
    sections.append(f"# Triage Memo: {memo.title}")
    sections.append("")
    sections.append(f"**Authors:** {memo.authors}")
    sections.append(f"**arXiv:** [{memo.arxiv_id}](https://arxiv.org/abs/{memo.arxiv_id})")
    sections.append(f"**Relevance:** {memo.relevance.value.upper()}")
    sections.append(f"**Decision:** {memo.read_decision}")
    if memo.tags:
        sections.append(f"**Tags:** {', '.join(memo.tags)}")
    sections.append("")

    # One-line summary
    sections.append(f"> {memo.one_line_summary}")
    sections.append("")

    # Key claims
    if memo.key_claims:
        sections.append("## Key Claims")
        for claim in memo.key_claims:
            sections.append(f"- {claim}")
        sections.append("")

    # Abstract
    sections.append("## Abstract")
    sections.append(memo.abstract)
    sections.append("")

    # Novelty report (score + novel contributions only; overlap goes below)
    if novelty_report is not None:
        sections.append("## Novelty Assessment")
        sections.append(f"**Novelty Score:** {novelty_report.novelty_score:.1f} / 1.0")
        sections.append("")
        if novelty_report.novel_contributions:
            sections.append("### Novel Contributions")
            for c in novelty_report.novel_contributions:
                sections.append(f"- {c}")
            sections.append("")

    # Overlap analysis: public prior art (S2) + your working papers (local)
    has_public = novelty_report is not None and (
        bool(novelty_report.overlap_notes) or bool(novelty_report.closest_prior_art)
    )
    has_local = local_overlap is not None and (
        bool(local_overlap.matches) or local_overlap.overall_relevance > 0
    )
    if has_public or has_local:
        sections.append("## Overlap Analysis")
        sections.append("")

        if novelty_report is not None and has_public:
            sections.append("### vs. public prior art (S2)")
            if novelty_report.overlap_notes:
                sections.append(novelty_report.overlap_notes)
                sections.append("")
            if novelty_report.closest_prior_art:
                sections.append("Closest prior art:")
                for p in novelty_report.closest_prior_art:
                    year_str = f" ({p.year})" if p.year else ""
                    cite_str = f" — {p.citation_count} citations" if p.citation_count else ""
                    sections.append(f"- {p.title}{year_str} — {p.authors}{cite_str}")
                sections.append("")
            sections.append("")

        if local_overlap is not None and has_local:
            sections.append("### vs. your working papers (local)")
            sections.append(
                f"**Overall relevance to your drafts:** {local_overlap.overall_relevance:.1f} / 1.0"
            )
            sections.append("")
            for m in local_overlap.matches:
                sections.append(f"- **{m.local_title}** (id: {m.local_id}, relevance: {m.relevance:.1f})")
                sections.append(f"  {m.overlap_summary}")
            sections.append("")

    # Related papers
    if memo.related_papers:
        sections.append("## Related Papers")
        for p in memo.related_papers:
            year_str = f" ({p.year})" if p.year else ""
            note = f" — *{p.relevance_note}*" if p.relevance_note else ""
            sections.append(f"- {p.title}{year_str}{note}")
        sections.append("")

    sections.append("---")
    sections.append("*Generated by Triage Memo Agent*")

    return "\n".join(sections)
