"""Markdown formatter for Triage Memos."""

from triage_agent.models.memo import TriageMemo


def render_markdown(memo: TriageMemo) -> str:
    """Render a TriageMemo as a readable Markdown document.

    Args:
        memo: The completed TriageMemo to format.

    Returns:
        A Markdown string ready for display or saving to file.
    """
    sections: list[str] = []

    # Header
    sections.append(f"# Triage Memo: {memo.title}")
    sections.append("")
    sections.append(f"**Authors:** {memo.authors}")
    sections.append(f"**arXiv:** [{memo.arxiv_id}](https://arxiv.org/abs/{memo.arxiv_id})")
    sections.append(f"**Relevance:** {memo.relevance.value.upper()}")
    sections.append(f"**Decision:** {memo.read_decision}")
    if memo.tags:
        sections.append(f"**Tags:** {', '.join(memo.tags)}")
    sections.append("")

    # One-line summary
    sections.append(f"> {memo.one_line_summary}")
    sections.append("")

    # Key claims
    if memo.key_claims:
        sections.append("## Key Claims")
        for claim in memo.key_claims:
            sections.append(f"- {claim}")
        sections.append("")

    # Abstract
    sections.append("## Abstract")
    sections.append(memo.abstract)
    sections.append("")

    # Method critique
    if memo.method_critique:
        mc = memo.method_critique
        sections.append("## Methodology Critique")
        sections.append(mc.summary)
        sections.append("")

        if mc.strengths:
            sections.append("### Strengths")
            for s in mc.strengths:
                sections.append(f"- {s}")
            sections.append("")

        if mc.break_points:
            sections.append("### Break Points")
            for bp in mc.break_points:
                severity_icon = {"critical": "[!]", "major": "[*]", "minor": "[-]"}.get(
                    bp.severity, "[ ]"
                )
                location = f" ({bp.location})" if bp.location else ""
                sections.append(f"- {severity_icon} **{bp.severity.upper()}**{location}: {bp.description}")
            sections.append("")

        if mc.assumptions:
            sections.append("### Key Assumptions")
            for a in mc.assumptions:
                sections.append(f"- {a}")
            sections.append("")

        if mc.verdict:
            sections.append(f"**Verdict:** {mc.verdict}")
            sections.append("")

    # Novelty report
    if memo.novelty_report:
        nr = memo.novelty_report
        sections.append("## Novelty Assessment")
        sections.append(f"**Novelty Score:** {nr.novelty_score:.1f} / 1.0")
        sections.append("")

        if nr.novel_contributions:
            sections.append("### Novel Contributions")
            for c in nr.novel_contributions:
                sections.append(f"- {c}")
            sections.append("")

        if nr.overlap_notes:
            sections.append("### Overlap with Prior Work")
            sections.append(nr.overlap_notes)
            sections.append("")

        if nr.closest_prior_art:
            sections.append("### Closest Prior Art")
            for p in nr.closest_prior_art:
                year_str = f" ({p.year})" if p.year else ""
                cite_str = f" [{p.citation_count} citations]" if p.citation_count else ""
                sections.append(f"- {p.title}{year_str} — {p.authors}{cite_str}")
            sections.append("")

    # Related papers
    if memo.related_papers:
        sections.append("## Related Papers")
        for p in memo.related_papers:
            year_str = f" ({p.year})" if p.year else ""
            note = f" — *{p.relevance_note}*" if p.relevance_note else ""
            sections.append(f"- {p.title}{year_str}{note}")
        sections.append("")

    sections.append("---")
    sections.append("*Generated by Triage Memo Agent*")

    return "\n".join(sections)
